git:
  quiet: true
  submodules: false

language: java
jdk: openjdk14

services: docker

jobs:
  include:
    - stage: unit tests
      name: "Java Unit Tests"
      script:
        - mvn clean test
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: functional tests
      name: "Python Functional Tests"
      before_install:
        - ./build-scripts/install-python.sh
      script:
        - ./build-scripts/build.sh
        - sleep 10
        - cd functional-tests/features
        - behave
        # TODO install awscli and push to ECR in after_success
